### ISSUE TITLE
New Prototype - targetedthreats (https://github.com/botherder/targetedthreats)

### ISSUE THREAD

**Issue by simonsigre** [PaloAltoNetworks/minemeld-node-prototypes#92]
As taken from "https://github.com/botherder/targetedthreats" and in specific the amazing work by Nex @botherder from Amnesty International.

"Collection of IOCs related to targeting of civil society."

Proposed file to parse:  `https://raw.githubusercontent.com/botherder/targetedthreats/master/targetedthreats.csv`

**Comment by simonsigre** [comment]
Proposed first draft prototype here.. to get ball rolling
```
    botherder_targetedthreats-ipv4:
        class: minemeld.ft.http.HttpFT
        config:
            attributes:
                confidence: 80
                share_level: green
                type: IPv4
            indicator:
		regex: '^\"([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\s*'
	    delimiter: ','
            fieldnames:
            - ioc
            - Family
            - Country
            - Reference
            ignore_regex: ^#.*
            interval: 3600
            source_name: botherder.targetedthreats
            url: https://raw.githubusercontent.com/botherder/targetedthreats/master/targetedthreats.csv
        description: 'Collection of IOCs related to targeting of civil society.

            https://github.com/botherder/targetedthreats'
        development_status: EXPERIMENTAL
        indicator_types:
        - IPv4
        node_type: miner
        tags:
        - ShareLevelGreen
        - ConfidenceHigh
```
Unsure how to properly set the delimiting to also support the fieldname encapsulation of `"`
